// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.24.0";

// src/lib/mcp/tools/get-profile.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.24.0";
var profile = {
  name: "Satyajit Patra",
  headline: "B.Tech Computer Science student at Government College of Engineering Kalahandi (GCEK)",
  year: "4th Year",
  focus: [
    "Software Development (Java, Python)",
    "Web Development",
    "AI & Machine Learning",
    "Database Management (SQL, Oracle)",
    "Cybersecurity"
  ],
  bio: "Passionate CS student focused on building innovative, real-world solutions. Experienced leading project teams during internships at OCAC and Edunet Foundation with IBM.",
  website: "https://satyajit-portfolio.lovable.app"
};
var get_profile_default = defineTool({
  name: "get_profile",
  title: "Get profile",
  description: "Return an overview of Satyajit Patra: name, education, focus areas, and short bio.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{ type: "text", text: JSON.stringify(profile, null, 2) }],
    structuredContent: profile
  })
});

// src/lib/mcp/tools/list-projects.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.24.0";
var projects = [
  {
    title: "Error Detection and Resolution System",
    year: "2024",
    role: "Project Leader",
    company: "OCAC Internship",
    technologies: ["Java", "NetBeans IDE 8.2", "Oracle Database"],
    description: "Built during the OCAC internship to help teams track and fix bugs faster, streamlining testing and team collaboration.",
    details: "https://github.com/satyajit-25/EDRS/blob/main/README.md",
    code: "https://github.com/satyajit-25/EDRS/tree/main/src/ocacjava2_6pm"
  },
  {
    title: "AI Computer Vision Toolkit",
    year: "2025",
    role: "AI Intern",
    company: "OCAC Internship",
    technologies: ["Python", "OpenCV", "MediaPipe", "Computer Vision"],
    description: "Virtual mouse and hand gesture detection system \u2014 control a computer with hand gestures, no touch required.",
    details: "https://github.com/satyajit-25/VisionMouse/blob/main/README.md",
    code: "https://github.com/satyajit-25/VisionMouse/blob/main/ai_virtual_mouse.py"
  },
  {
    title: "Employee Salary Prediction",
    year: "2025",
    role: "ML Intern",
    company: "Edunet Foundation with IBM",
    technologies: ["Python", "Machine Learning", "Pandas", "Scikit-learn"],
    description: "Machine-learning project predicting salaries from multiple factors, deployed as a Streamlit web app.",
    details: "https://github.com/satyajit-25/Employee-salary-prediction/blob/main/README.md",
    code: "https://github.com/satyajit-25/Employee-salary-prediction/blob/main/app.py"
  }
];
var list_projects_default = defineTool2({
  name: "list_projects",
  title: "List projects",
  description: "List projects Satyajit has built, with technologies, role, company, and links.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{ type: "text", text: JSON.stringify(projects, null, 2) }],
    structuredContent: { projects }
  })
});

// src/lib/mcp/tools/list-skills.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.24.0";
var skills = [
  { category: "Programming Languages", items: [{ name: "Java", level: 90 }, { name: "Python", level: 85 }] },
  { category: "Web Development", items: [{ name: "HTML", level: 95 }, { name: "CSS", level: 90 }, { name: "JavaScript", level: 85 }] },
  { category: "Database Management", items: [{ name: "SQL", level: 90 }, { name: "Oracle", level: 85 }] },
  { category: "Core Concepts", items: [{ name: "Data Structures", level: 88 }, { name: "Algorithms", level: 85 }, { name: "OOP", level: 92 }] },
  { category: "Tools & Technologies", items: [{ name: "Git", level: 90 }, { name: "GitHub", level: 88 }, { name: "AI Concepts", level: 75 }] }
];
var list_skills_default = defineTool3({
  name: "list_skills",
  title: "List skills",
  description: "Return Satyajit's technical skills grouped by category, with proficiency levels (0-100).",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{ type: "text", text: JSON.stringify(skills, null, 2) }],
    structuredContent: { skills }
  })
});

// src/lib/mcp/tools/list-services.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.24.0";
var services = [
  {
    title: "Web Development",
    description: "Responsive, user-friendly websites and web apps using modern frameworks and best practices.",
    features: ["Responsive Design", "Modern Frameworks", "Performance Optimization", "Cross-browser Compatibility"]
  },
  {
    title: "Software Development",
    description: "Robust software in Java and Python, focused on scalability and maintainability.",
    features: ["Object-Oriented Programming", "Algorithm Design", "Code Optimization", "Testing & Debugging"]
  },
  {
    title: "Database Solutions",
    description: "Efficient database systems with SQL and Oracle for optimal data management.",
    features: ["Database Design", "Query Optimization", "Data Migration", "Performance Tuning"]
  },
  {
    title: "AI & Machine Learning",
    description: "Applied ML solutions for intelligent automation and data-driven insight.",
    features: ["AI Algorithm Implementation", "Data Analysis", "Predictive Modeling", "Automation Solutions"]
  }
];
var list_services_default = defineTool4({
  name: "list_services",
  title: "List services",
  description: "List the services Satyajit offers, with descriptions and feature highlights.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{ type: "text", text: JSON.stringify(services, null, 2) }],
    structuredContent: { services }
  })
});

// src/lib/mcp/tools/get-contact.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.24.0";
var contact = {
  email: "satyajit.patra203@gmail.com",
  phone: "+91 79782 72616",
  linkedin: "https://linkedin.com/in/satyajit-patra-a33403323",
  github: "https://github.com/satyajit-25",
  website: "https://satyajit-portfolio.lovable.app"
};
var get_contact_default = defineTool5({
  name: "get_contact",
  title: "Get contact info",
  description: "Return public contact channels for Satyajit: email, phone, LinkedIn, GitHub, and website.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{ type: "text", text: JSON.stringify(contact, null, 2) }],
    structuredContent: contact
  })
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "satyajit-portfolio-mcp",
  title: "Satyajit Patra \u2014 Portfolio",
  version: "0.1.0",
  instructions: "Public MCP server for Satyajit Patra's portfolio. Use these tools to answer questions about his profile, projects, skills, services, and contact info.",
  tools: [get_profile_default, list_projects_default, list_skills_default, list_services_default, get_contact_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.24.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
